version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bia123
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=biancadefaria133@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=bia123
    ports:
      - "5050:80"
    restart: always
